### ISSUE TITLE
Error: Prefix fasta file does not exist! Please check output path

### ISSUE THREAD

**Issue by HLHsieh** [Boyle-Lab/HMMSTR_depreciated#1]
Hi Kinsey,

I am interested in these exciting tools. I was trying to apply it to my data as follows:

```
hmmstr targets_tsv input.txt ./C9ORF72 C9ORF72_1.fasta
```

The error shows:
```
Prefix fasta file does not exist! Please check output path
Prefix fasta file does not exist! Please check output path
Prefix fasta file does not exist! Please check output path
Prefix fasta file does not exist! Please check output path
Prefix fasta file does not exist! Please check output path
Prefix fasta file does not exist! Please check output path
Prefix fasta file does not exist! Please check output path
```
I have C9ORF72_1.fasta and input.txt in my working directory.

I have no idea how to resolve this. I would appreciate any comments on this.

Best,
Hsin

**Comment by kvandeynze** [comment]
Hi Hsin,
First thank you for your interest in trying out HMMSTR! This error is thrown when the prefix.fa file does not exist. This may occur when there are no prefixes and/or suffixes detected in the input tsv. To solve this I would ensure that your input file contains both the expected header (name, prefix, repeat, suffix in tab delimited format) as well as at least one intended target. Please let us know if you have any other issues!
